# Generated by Django 4.0.3 on 2022-05-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdeskapp', '0005_alter_contributors_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('C', 'CRUD'), ('R', 'READ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='softdeskapp.projects'),
        ),
    ]
