# Generated by Django 4.0.3 on 2022-05-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdeskapp', '0006_alter_contributors_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='softdeskapp.projects'),
        ),
    ]
