# Generated by Django 4.0.3 on 2022-05-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdeskapp', '0007_alter_issues_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='softdeskapp.issues'),
        ),
    ]
